image: node:8.6.0

stages:
  - deploy

deploying:
  image: node:8.6.0
  stage: deploy
  script:
    - "ELEMENT_TITLE=`node -e \"var manifest = require('./manifest.json');console.log(manifest.elements[Object.keys(manifest.elements)[0]].settings.name);\"`"
    - "echo \"$CI_HUB_GROUP_TEST_DOMAIN/api/inner/bundle/create?key=$CI_HUB_GROUP_ELEMENTS_BUILD_KEY&bundle=element/$CI_PROJECT_NAME&version=latest&name=$ELEMENT_TITLE\""
    - "curl -X GET -H 'Content-type: application/json' \"$CI_HUB_GROUP_TEST_DOMAIN/api/inner/bundle/create?key=$CI_HUB_GROUP_ELEMENTS_BUILD_KEY&bundle=element/$CI_PROJECT_NAME&version=latest&name=$ELEMENT_TITLE\""
  tags:
    - docker